name: CookieMonster
main: com.pi.coelho.CookieMonster.CookieMonster
version: 1.3.3
authors: [jascotty2, Coelho]
commands:
  cookiemonster:
    description: Admin Commands
    usage: /<command> [reload]
    aliases: [cm]